# Generated by Django 4.1.1 on 2022-10-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idReserva', models.CharField(max_length=50)),
                ('nombreSolicitante', models.CharField(max_length=50)),
                ('fono', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('RESERVADO', 'RESERVADO'), ('COMPLETADA', 'COMPLETADA'), ('ANULADA', 'ANULADA'), ('NO ASISTEN', 'NO ASISTEN')], max_length=10)),
                ('cantidadPersonas', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15')], max_length=2)),
                ('observacion', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
